sudo: required
services:
  - docker
language: go
go: 1.13
gobuild_args: -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a

env:
  - TERRAFORM_VERSION=0.11.14
  - TERRAFORM_VERSION=0.12.8
  - TERRAFORM_VERSION=0.12.9
  - TERRAFORM_VERSION=0.12.10
  - TERRAFORM_VERSION=0.12.11

before_deploy:
  - docker build . -t robertstettner/drone-tf-outputs-to-env:${TRAVIS_TAG}-${TERRAFORM_VERSION} --build-arg terraform_version=${TERRAFORM_VERSION}
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
